export default {
  // This is the connection point of our React project into our backend, Python project. Here, we refer to the 
  // adresses that are defined in backend. Those adresses are called by services that are located in services.js

  add: "/add",
  fetchDB: "/fetchdb",
  createPart: "/createPart",
  getAllParts: "/getAllParts",
  createQuestion: "/createQuestion",
  getAllQuestions: "/getAllQuestions",
  creatingNewAccount: "/creatingNewAccount",
  loginAccount: "/loginAccount",
  createNewAdminAccount: "/createNewAdminAccount",
  createNewSuperAdminAccount: "/createNewSuperAdminAccount",
  changePassword: "/changePassword",
  deletePart: "/deletePart",
  deleteQuestion: "/deleteQuestion",
  submitNewPassword: "submitNewPassword",
  createAssessmentSession: "/createAssessmentSession",
  uploadUserAnswers: "/uploadUserAnswers",
  saveImage: "/saveImage",
  getImages: "/getImages",
  updateImageFromIndex: "/updateImageFromIndex",
  deleteImageFromIndex: "/deleteImageFromIndex",
  removeAllImages: "/removeAllImages",
  saveImageInfoPage: "/saveImageInfoPage",
  getImagesInfoPage: "/getImagesInfoPage",
  updateImageFromIndexInfoPage: "/updateImageFromIndexInfoPage",
  deleteImageFromIndexInfoPage: "/deleteImageFromIndexInfoPage",
  removeAllImagesInfoPage: "/removeAllImagesInfoPage",
  saveImageRiskPage: "/saveImageRiskPage",
  getImagesRiskPage: "/getImagesRiskPage",
  updateImageFromIndexRiskPage: "/updateImageFromIndexRiskPage",
  deleteImageFromIndexRiskPage: "/deleteImageFromIndexRiskPage",
  removeAllImagesRiskPage: "/removeAllImagesRiskPage",
  saveVideo: "/saveVideo",
  getVideos: "/getVideos",
  getAssessments: "/getAssessments",
  getAllAssessments: "/getAllAssessments",
  getAllAnswers: "/getAllAnswers",
  evaluate: "/evaluate",
  saveDataAsExcel: "/saveDataAsExcel",
  getSuggestionsByAssessmentId: "/getSuggestionsByAssessmentId",
  getSuggestionsContent: "/getSuggestionsContent",
  getAnswerPercentage: "/getAnswerPercentage",
  getTotalPeopleCount: "/getTotalPeopleCount",
};
