export default {
    add: '/add',
    fetchDB: '/fetchdb',
    createPart: '/createPart',
    getAllParts: '/getAllParts',
    createQuestion: '/createQuestion',
    getAllQuestions: '/getAllQuestions',
    creatingNewAccount: '/creatingNewAccount',
    loginAccount: '/loginAccount',
    createNewAdminAccount: '/createNewAdminAccount',
    createNewSuperAdminAccount: '/createNewSuperAdminAccount',
    changePassword: '/changePassword',
    deletePart: '/deletePart',
    deleteQuestion: '/deleteQuestion',
    submitNewPassword: 'submitNewPassword',
    createAssessmentSession: '/createAssessmentSession',
    uploadUserAnswers: '/uploadUserAnswers',
    saveImage: '/saveImage',
    getImages: '/getImages',
    updateImageFromIndex: '/updateImageFromIndex',
    deleteImageFromIndex: '/deleteImageFromIndex',
};